
import { VocabularyPack } from './types';

export const VOCABULARY_PACKS: VocabularyPack[] = [
  {
    id: 'kitchen',
    title: 'La Mia Cucina',
    subtitle: 'Kitchen Items',
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745a872f?q=80&w=1470&auto=format&fit=crop',
    icon: 'countertops',
    items: [
      { italian: 'Il tavolo', english: 'The table', urdu: 'میز' },
      { italian: 'La sedia', english: 'The chair', urdu: 'کرسی' },
      { italian: 'Il forno', english: 'The oven', urdu: 'اوون' },
      { italian: 'Il frigorifero', english: 'The refrigerator', urdu: 'فریج' },
      { italian: 'Il coltello', english: 'The knife', urdu: 'چاقو' },
      { italian: 'La forchetta', english: 'The fork', urdu: 'کانٹا' },
      { italian: 'Il cucchiaio', english: 'The spoon', urdu: 'چمچ' },
      { italian: 'La tazza', english: 'The cup', urdu: 'پیالی' },
      { italian: 'Il piatto', english: 'The plate', urdu: 'پلیٹ' },
      { italian: 'Il bicchiere', english: 'The glass', urdu: 'گلاس' },
      { italian: 'La ciotola', english: 'The bowl', urdu: 'پیالہ' },
      { italian: 'Il tovagliolo', english: 'The napkin', urdu: 'رومال' },
      { italian: 'Il bollitore', english: 'The kettle', urdu: 'کیتلی' },
      { italian: 'La padella', english: 'The pan', urdu: 'فرائی پین' },
      { italian: 'Il microonde', english: 'The microwave', urdu: 'مائیکرو ویو' },
      { italian: 'La frusta', english: 'The whisk', urdu: 'پھینٹنی' },
      { italian: 'Il frullatore', english: 'The blender', urdu: 'بلینڈر' },
      { italian: 'Il tostapane', english: 'The toaster', urdu: 'ٹوسٹر' },
      { italian: 'La saliera', english: 'The salt shaker', urdu: 'نمک دانی' },
      { italian: 'Il macinapepe', english: 'The pepper mill', urdu: 'کالی مرچ پیسنے والی مشین' },
      { italian: 'Il grembiule', english: 'The apron', urdu: 'پیش بند' },
      { italian: 'Il rubinetto', english: 'The faucet', urdu: 'نل' },
      { italian: 'La lavastoviglie', english: 'The dishwasher', urdu: 'برتن دھونے والی مشین' },
      { italian: 'Il fornello', english: 'The stove', urdu: 'چولہا' },
      { italian: 'La cappa', english: 'The extractor hood', urdu: 'ہوا نکالنے والا ہڈ' },
      { italian: 'Il cavatappi', english: 'The corkscrew', urdu: 'بوتل کھولنے والا آلہ' },
      { italian: 'Il tagliere', english: 'The cutting board', urdu: 'کاٹنے والا بورڈ' },
      { italian: 'Il pelapatate', english: 'The peeler', urdu: 'چھلنی' },
      { italian: 'La grattugia', english: 'The grater', urdu: 'کدوکش' },
      { italian: 'La bilancia', english: 'The scale', urdu: 'ترازو' },
      { italian: 'Il timer', english: 'The timer', urdu: 'وقت بتانے والا آلہ' },
      { italian: 'Il vassoio', english: 'The tray', urdu: 'ٹرے' },
      { italian: 'Il barattolo', english: 'The jar', urdu: 'مرتبان' },
      { italian: 'Il coperchio', english: 'The lid', urdu: 'ڈھکن' },
      { italian: 'Il boccale', english: 'The mug', urdu: 'مگ' },
      { italian: 'La caffettiera', english: 'The coffee maker', urdu: 'کافی بنانے والی مشین' },
      { italian: 'L\'armadietto', english: 'The cupboard', urdu: 'الماری' },
      { italian: 'Il cassetto', english: 'The drawer', urdu: 'دراز' },
      { italian: 'Lo scaffale', english: 'The shelf', urdu: 'شیلف' },
      { italian: 'La spugna', english: 'The sponge', urdu: 'سپنج' },
      { italian: 'Il detersivo', english: 'The dish soap', urdu: 'برتن دھونے کا صابن' },
      { italian: 'Lo scolapiatti', english: 'The drying rack', urdu: 'برتن خشک کرنے والا اسٹینڈ' },
      { italian: 'Il guanto', english: 'The glove', urdu: 'دستانہ' },
      { italian: 'La presina', english: 'The potholder', urdu: 'پکڑنے والا کپڑا' },
      { italian: 'I fiammiferi', english: 'The matches', urdu: 'ماچس' },
      { italian: 'L\'accendino', english: 'The lighter', urdu: 'لائٹر' },
      { italian: 'Lo schiaccia-aglio', english: 'The garlic press', urdu: 'لہسن پیسنے والا آلہ' },
      { italian: 'Il mattarello', english: 'The rolling pin', urdu: 'بیلن' },
      { italian: 'Il mortaio', english: 'The mortar', urdu: 'امام دستہ' },
      { italian: 'Lo scolapasta', english: 'The colander', urdu: 'چھلنی (پاستا کے لیے)' },
      { italian: 'Il setaccio', english: 'The sieve', urdu: 'چھلنی (آٹے کے لیے)' },
      { italian: 'L\'imbuto', english: 'The funnel', urdu: 'قیف' },
      { italian: 'Il misurino', english: 'The measuring cup', urdu: 'ناپنے والا کپ' },
      { italian: 'Il pennello', english: 'The basting brush', urdu: 'برش' },
      { italian: 'La spatola', english: 'The spatula', urdu: 'چمچہ' },
      { italian: 'Le pinze', english: 'The tongs', urdu: 'چماٹا' },
      { italian: 'Il mestolo', english: 'The ladle', urdu: 'بڑا چمچہ' },
      { italian: 'La schiumarola', english: 'The skimmer', urdu: 'جھاگ نکالنے والا چمچہ' },
      { italian: 'La rotella tagliapizza', english: 'The pizza cutter', urdu: 'پیزا کاٹنے والا آلہ' },
      { italian: 'L\'apriscatole', english: 'The can opener', urdu: 'ڈبہ کھولنے والا آلہ' },
      { italian: 'L\'apribottiglie', english: 'The bottle opener', urdu: 'بوتل کھولنے والا' },
      { italian: 'Il calice', english: 'The wine glass', urdu: 'شراب کا گلاس' },
      { italian: 'Il flute', english: 'The champagne flute', urdu: 'لیمبی شکل کا گلاس' },
      { italian: 'La teglia', english: 'The baking sheet', urdu: 'بیکنگ ٹرے' },
      { italian: 'La pentola', english: 'The pot', urdu: 'دیگچی' },
      // 50 additional kitchen words
      { italian: 'La moka', english: 'Espresso pot', urdu: 'کافی بنانے والا برتن' },
      { italian: 'Il frullatore ad immersione', english: 'Immersion blender', urdu: 'ہینڈ بلینڈر' },
      { italian: 'Lo strofinaccio', english: 'Dishcloth', urdu: 'برتن صاف کرنے والا کپڑا' },
      { italian: 'La pentola a pressione', english: 'Pressure cooker', urdu: 'پریشر ککر' },
      { italian: 'Il portaspezie', english: 'Spice rack', urdu: 'مصالحہ دان' },
      { italian: 'Il tappo', english: 'The stopper', urdu: 'ڈاٹ' },
      { italian: 'Il termometro da cucina', english: 'Kitchen thermometer', urdu: 'کچن تھرمامیٹر' },
      { italian: 'La caraffa', english: 'The carafe', urdu: 'صراحی' },
      { italian: 'Il colino', english: 'The strainer', urdu: 'چھلنی' },
      { italian: 'Lo schiacciapatate', english: 'Potato masher', urdu: 'آلو پیسنے والا' },
      { italian: 'Il cestino del pane', english: 'Bread basket', urdu: 'روٹی کی ٹوکری' },
      { italian: 'Il grill', english: 'The grill', urdu: 'گرل' },
      { italian: 'La bilancia digitale', english: 'Digital scale', urdu: 'ڈیجیٹل ترازو' },
      { italian: 'Il sifone', english: 'The siphon', urdu: 'سائفن' },
      { italian: 'La gratella', english: 'The cooling rack', urdu: 'ٹھنڈا کرنے والا ریک' },
      { italian: 'Lo stampo da forno', english: 'Baking mold', urdu: 'بیکنگ مولڈ' },
      { italian: 'Il sac à poche', english: 'Pastry bag', urdu: 'پیسٹری بیگ' },
      { italian: 'Il mestolo per spaghetti', english: 'Spaghetti server', urdu: 'سپتیٹی والا چمچہ' },
      { italian: 'La paletta', english: 'The turner', urdu: 'پلٹا' },
      { italian: 'Il cucchiaio di legno', english: 'Wooden spoon', urdu: 'لکڑی کا چمچہ' },
      { italian: 'Il pela carote', english: 'Carrot peeler', urdu: 'گاجر چھیلنے والا' },
      { italian: 'Il trinciapollo', english: 'Poultry shears', urdu: 'مرغی کاٹنے والی قینچی' },
      { italian: 'Lo sbucciatore', english: 'The peeler', urdu: 'چھلنی' },
      { italian: 'La griglia', english: 'The grid', urdu: 'جالی' },
      { italian: 'Il cestino dei rifiuti', english: 'Trash bin', urdu: 'کچرے کا ڈبہ' },
      { italian: 'Il sacchetto', english: 'The bag', urdu: 'تھیلی' },
      { italian: 'La pellicola trasparente', english: 'Cling film', urdu: 'کلنگ فلم' },
      { italian: 'La carta stagnola', english: 'Aluminum foil', urdu: 'ایلومینیم فوائل' },
      { italian: 'La carta da forno', english: 'Parchment paper', urdu: 'بیکنگ پیپر' },
      { italian: 'Il detersivo per piatti', english: 'Dish soap', urdu: 'برتن دھونے والا صابن' },
      { italian: 'La luffa', english: 'Kitchen loofah', urdu: 'کچن سپنج' },
      { italian: 'Il panno in microfibra', english: 'Microfiber cloth', urdu: 'مائیکرو فائبر کپڑا' },
      { italian: 'Lo spruzzino', english: 'Spray bottle', urdu: 'سپرے بوتل' },
      { italian: 'L\'oliera', english: 'Oil cruet', urdu: 'تیل کا برتن' },
      { italian: 'L\'acetiera', english: 'Vinegar cruet', urdu: 'سرکہ کا برتن' },
      { italian: 'Il portatovaglioli', english: 'Napkin holder', urdu: 'نیپکن ہولڈر' },
      { italian: 'La zuccheriera', english: 'Sugar bowl', urdu: 'شکر دانی' },
      { italian: 'La lattiera', english: 'Milk jug', urdu: 'دودھ کا برتن' },
      { italian: 'Il bollitore elettrico', english: 'Electric kettle', urdu: 'برقی کیتلی' },
      { italian: 'Il macinacaffè', english: 'Coffee grinder', urdu: 'کافی پیسنے والی مشین' },
      { italian: 'La centrifuga per insalata', english: 'Salad spinner', urdu: 'سلاد خشک کرنے والا' },
      { italian: 'Il mortaio con pestello', english: 'Mortar and pestle', urdu: 'امام دستہ' },
      { italian: 'Lo schiaccianoci', english: 'Nutcracker', urdu: 'اخروٹ توڑنے والا' },
      { italian: 'Il colino a maglia fine', english: 'Fine mesh sieve', urdu: 'باریک چھلنی' },
      { italian: 'La bistecchiera', english: 'Griddle pan', urdu: 'گرل پین' },
      { italian: 'La vaporiera', english: 'Steamer', urdu: 'سٹیمر' },
      { italian: 'La wok', english: 'The wok', urdu: 'کڑھائی' },
      { italian: 'Il vasetto di spezie', english: 'Spice jar', urdu: 'مصالحہ جار' },
      { italian: 'La crepiera', english: 'Crepe pan', urdu: 'کریپ پین' },
      { italian: 'Il mestolo forato', english: 'Slotted spoon', urdu: 'سوراخ دار چمچہ' }
    ]
  },
  {
    id: 'bathroom',
    title: 'Bagno',
    subtitle: 'Bathroom',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1470&auto=format&fit=crop',
    icon: 'bathroom',
    items: [
      { italian: 'La doccia', english: 'The shower', urdu: 'شاور' },
      { italian: 'Lo specchio', english: 'The mirror', urdu: 'آئینہ' },
      { italian: 'Il sapone', english: 'The soap', urdu: 'صابن' },
      { italian: 'L\'asciugamano', english: 'The towel', urdu: 'تولیہ' },
      { italian: 'Lo spazzolino', english: 'The toothbrush', urdu: 'ٹوتھ برش' },
      { italian: 'Il dentifricio', english: 'The toothpaste', urdu: 'ٹوتھ پیسٹ' },
      { italian: 'Il lavandino', english: 'The sink', urdu: 'واش بیسن' },
      { italian: 'Il gabinetto', english: 'The toilet', urdu: 'ٹوائلٹ' },
      { italian: 'L\'accappatoio', english: 'The bathrobe', urdu: 'غسل کا لباس' },
      { italian: 'L\'asciugacapelli', english: 'The hairdryer', urdu: 'ہیئر ڈرائر' },
      { italian: 'Lo shampoo', english: 'The shampoo', urdu: 'شیمپو' },
      { italian: 'Il pettine', english: 'The comb', urdu: 'کنگھی' },
      { italian: 'La carta igienica', english: 'The toilet paper', urdu: 'ٹوالیٹ پیپر' },
      { italian: 'La vasca', english: 'The bathtub', urdu: 'ٹب' },
      { italian: 'Il tappetino', english: 'The bath mat', urdu: 'غسل خانے کا قالین' },
      { italian: 'La bilancia', english: 'The scales', urdu: 'ترازو' },
      { italian: 'Il rasoio', english: 'The razor', urdu: 'استرا' },
      { italian: 'La schiuma da barba', english: 'The shaving cream', urdu: 'شیو کریم' },
      { italian: 'Il dopobarba', english: 'The aftershave', urdu: 'شیو کے بعد لگانے والا لوشن' },
      { italian: 'Il profumo', english: 'The perfume', urdu: 'خوشبو' },
      { italian: 'La crema idratante', english: 'The moisturizer', urdu: 'موئسچرائزر' },
      { italian: 'La lozione', english: 'The lotion', urdu: 'لوشن' },
      { italian: 'La crema solare', english: 'The sunscreen', urdu: 'سن اسکرین' },
      { italian: 'I cotton fioc', english: 'The cotton buds', urdu: 'کان صاف کرنے والی تیلیاں' },
      { italian: 'I dischetti di cotone', english: 'The cotton pads', urdu: 'روئی کے پیڈ' },
      { italian: 'Lo struccante', english: 'The makeup remover', urdu: 'میک اپ صاف کرنے والا' },
      { italian: 'La lima per unghie', english: 'The nail file', urdu: 'ناخنوں کا ریگ مال' },
      { italian: 'Le pinzette', english: 'The tweezers', urdu: 'چمٹی' },
      { italian: 'Le forbici', english: 'The scissors', urdu: 'قینچی' },
      { italian: 'La benda', english: 'The bandage', urdu: 'پٹی' },
      { italian: 'Il cerotto', english: 'The plaster', urdu: 'پلستر' },
      { italian: 'Il distributore di sapone', english: 'The soap dispenser', urdu: 'صابن نکالنے والا آلہ' },
      { italian: 'I fazzoletti', english: 'The tissues', urdu: 'ٹشو' },
      { italian: 'Il cestino', english: 'The trash can', urdu: 'کوڑے دان' },
      { italian: 'Lo stantuffo', english: 'The plunger', urdu: 'ٹوائلٹ صاف کرنے والا پمپ' },
      { italian: 'Lo scopino', english: 'The toilet brush', urdu: 'ٹوائلٹ صاف کرنے والا برش' },
      { italian: 'La piastrella', english: 'The tile', urdu: 'ٹائل' },
      { italian: 'Le ciabatte', english: 'The slippers', urdu: 'چپل' },
      { italian: 'Il portasapone', english: 'The soap dish', urdu: 'صابن دانی' },
      { italian: 'Il filo interdentale', english: 'The dental floss', urdu: 'دانت صاف کرنے والا دھاگہ' },
      { italian: 'Il collutorio', english: 'The mouthwash', urdu: 'ماؤتھ واش' },
      { italian: 'La bomba da bagno', english: 'The bath bomb', urdu: 'غسل کا بم' },
      { italian: 'La spugna di luffa', english: 'The loofah', urdu: 'لائفہ' },
      { italian: 'La pietra pomice', english: 'The pumice stone', urdu: 'جھاواں' },
      { italian: 'Lo spazzolino per unghie', english: 'The nail brush', urdu: 'ناخنوں کا برش' },
      { italian: 'Il cesto della biancheria', english: 'The laundry basket', urdu: 'لانڈری ٹوکری' },
      { italian: 'La candeggina', english: 'The bleach', urdu: 'بلیچ' },
      { italian: 'Il detersivo', english: 'The detergent', urdu: 'سرف' },
      { italian: 'L\'ammorbidente', english: 'The fabric softener', urdu: 'کپڑے نرم کرنے والا' },
      { italian: 'Il mocio', english: 'The mop', urdu: 'پوچا' },
      { italian: 'Il secchio', english: 'The bucket', urdu: 'بالٹی' },
      { italian: 'Lo straccio', english: 'The rag', urdu: 'پرانا کپڑا' },
      { italian: 'L\'armadietto a specchio', english: 'The mirror cabinet', urdu: 'آئینے والی الماری' },
      { italian: 'L\'interruttore', english: 'The light switch', urdu: 'بجلی کا سوئچ' },
      { italian: 'La ventola', english: 'The fan', urdu: 'پنکھا' },
      { italian: 'La crema per mani', english: 'Hand cream', urdu: 'ہاتھوں کی کریم' },
      { italian: 'Il balsamo', english: 'Conditioner', urdu: 'کنڈیشنر' },
      { italian: 'La cuffia', english: 'Shower cap', urdu: 'شاور کیپ' },
      { italian: 'Il bidet', english: 'The bidet', urdu: 'بائیڈے' },
      { italian: 'La spugna', english: 'The sponge', urdu: 'سپنج' },
      { italian: 'Il bicchiere', english: 'The glass', urdu: 'گلاس' },
      { italian: 'La maniglia', english: 'The handle', urdu: 'ہینڈل' },
      { italian: 'La spazzola', english: 'The brush', urdu: 'برش' },
      // 50 additional bathroom words
      { italian: 'L\'idromassaggio', english: 'The whirlpool', urdu: 'ہائیڈروماساج' },
      { italian: 'Lo specchio ingranditore', english: 'Magnifying mirror', urdu: 'بڑا دکھانے والا آئینہ' },
      { italian: 'Il tappo del lavandino', english: 'Sink plug', urdu: 'سنگ کا ڈھکن' },
      { italian: 'La doccetta', english: 'Hand shower', urdu: 'ہینڈ شاور' },
      { italian: 'Il soffione della doccia', english: 'Shower head', urdu: 'شاور ہیڈ' },
      { italian: 'La tenda della doccia', english: 'Shower curtain', urdu: 'شاور کا پردہ' },
      { italian: 'Il portascarpe', english: 'Shoe rack', urdu: 'جوتا ریک' },
      { italian: 'La salvietta', english: 'Hand towel', urdu: 'ہاتھ کا تولیہ' },
      { italian: 'L\'asciugamano ospite', english: 'Guest towel', urdu: 'مہمان کا تولیہ' },
      { italian: 'Lo smalto per unghie', english: 'Nail polish', urdu: 'ناخن پالش' },
      { italian: 'Il solvente', english: 'Nail polish remover', urdu: 'نیل پالش ریموور' },
      { italian: 'La lacca per capelli', english: 'Hairspray', urdu: 'ہیئر سپرے' },
      { italian: 'Il gel per capelli', english: 'Hair gel', urdu: 'ہیئر جیل' },
      { italian: 'La schiuma per capelli', english: 'Hair mousse', urdu: 'ہیئر موس' },
      { italian: 'La crema per il corpo', english: 'Body cream', urdu: 'باڈی کریم' },
      { italian: 'Il bagnoschiuma', english: 'Bubble bath', urdu: 'ببل باتھ' },
      { italian: 'L\'olio da bagno', english: 'Bath oil', urdu: 'نہانے کا تیل' },
      { italian: 'I sali da bagno', english: 'Bath salts', urdu: 'نہانے کا نمک' },
      { italian: 'Il deodorante', english: 'Deodorant', urdu: 'ڈیوڈرنٹ' },
      { italian: 'Il talco', english: 'Talcum powder', urdu: 'ٹالکم پاؤڈر' },
      { italian: 'La spazzola per capelli', english: 'Hairbrush', urdu: 'بالوں کا برش' },
      { italian: 'L\'elastico per capelli', english: 'Hair tie', urdu: 'بالوں کا چھلا' },
      { italian: 'La pinza per capelli', english: 'Hair clip', urdu: 'بالوں کا کلپ' },
      { italian: 'Il bigodino', english: 'Hair curler', urdu: 'بالوں کا رولر' },
      { italian: 'La piastra per capelli', english: 'Hair straightener', urdu: 'بال سیدھے کرنے والا' },
      { italian: 'L\'arricciacapelli', english: 'Curling iron', urdu: 'بال گھنگریالے کرنے والا' },
      { italian: 'Il mascara', english: 'Mascara', urdu: 'مسکارا' },
      { italian: 'L\'ombretto', english: 'Eyeshadow', urdu: 'آئی شیڈو' },
      { italian: 'Il fondotinta', english: 'Foundation', urdu: 'فاؤنڈیشن' },
      { italian: 'Il rossetto', english: 'Lipstick', urdu: 'لپ اسٹک' },
      { italian: 'Il burrocacao', english: 'Lip balm', urdu: 'لبوں کا بام' },
      { italian: 'La cipria', english: 'Face powder', urdu: 'فیس پاؤڈر' },
      { italian: 'Il fard', english: 'Blush', urdu: 'بلش' },
      { italian: 'L\'eyeliner', english: 'Eyeliner', urdu: 'آئی لائنر' },
      { italian: 'La matita per occhi', english: 'Eye pencil', urdu: 'آنکھوں کی پنسل' },
      { italian: 'Il correttore', english: 'Concealer', urdu: 'کنسیلر' },
      { italian: 'La spugnetta per trucco', english: 'Makeup sponge', urdu: 'میک اپ سپنج' },
      { italian: 'Il pennello da trucco', english: 'Makeup brush', urdu: 'میک اپ برش' },
      { italian: 'Il piegaciglia', english: 'Eyelash curler', urdu: 'پلکیں موڑنے والا' },
      { italian: 'Le ciglia finte', english: 'Fake eyelashes', urdu: 'مصنوعی پلکیں' },
      { italian: 'La trousse', english: 'Makeup bag', urdu: 'میک اپ بیگ' },
      { italian: 'Il disinfettante', english: 'Disinfectant', urdu: 'جراثیم کش' },
      { italian: 'L\'acqua ossigenata', english: 'Hydrogen peroxide', urdu: 'ہائیڈروجن پراکسائیڈ' },
      { italian: 'L\'alcol etilico', english: 'Ethyl alcohol', urdu: 'ایتھائل الکحل' },
      { italian: 'Il termometro', english: 'Thermometer', urdu: 'تھرمامیٹر' },
      { italian: 'Le vitamine', english: 'Vitamins', urdu: 'وٹامنز' },
      { italian: 'Le compresse', english: 'Tablets', urdu: 'گولیاں' },
      { italian: 'Lo sciroppo', english: 'Syrup', urdu: 'شربت' },
      { italian: 'La pomata', english: 'Ointment', urdu: 'مرہم' },
      { italian: 'Le gocce', english: 'Drops', urdu: 'قطرے' }
    ]
  },
  {
    id: 'vegetables',
    title: 'Verdura',
    subtitle: 'Vegetables',
    imageUrl: 'https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?q=80&w=1632&auto=format&fit=crop',
    icon: 'nutrition',
    items: [
      { italian: 'La carota', english: 'The carrot', urdu: 'گاجر' },
      { italian: 'Il pomodoro', english: 'The tomato', urdu: 'ٹماٹر' },
      { italian: 'La patata', english: 'The potato', urdu: 'آلو' },
      { italian: 'La cipolla', english: 'The onion', urdu: 'پیاز' },
      { italian: 'Il cetriolo', english: 'The cucumber', urdu: 'کھیرا' },
      { italian: 'I broccoli', english: 'The broccoli', urdu: 'بروکولی' },
      { italian: 'L\'insalata', english: 'The salad', urdu: 'سلاد' },
      { italian: 'L\'aglio', english: 'The garlic', urdu: 'لہسن' },
      { italian: 'Gli spinaci', english: 'The spinach', urdu: 'پالک' },
      { italian: 'La melanzana', english: 'The eggplant', urdu: 'بینگن' },
      { italian: 'Lo zucchino', english: 'The zucchini', urdu: 'کدو' },
      { italian: 'Il peperone', english: 'The pepper', urdu: 'شملہ مرچ' },
      { italian: 'Il mais', english: 'The corn', urdu: 'مکئی' },
      { italian: 'I piselli', english: 'The peas', urdu: 'مٹر' },
      { italian: 'Il cavolfiore', english: 'The cauliflower', urdu: 'پھول گوبھی' },
      { italian: 'Il cavolo', english: 'The cabbage', urdu: 'بند گوبھی' },
      { italian: 'I cavoletti di Bruxelles', english: 'Brussels sprouts', urdu: 'برسلز اسپراؤٹس' },
      { italian: 'Il cavolo riccio', english: 'Kale', urdu: 'کئیل' },
      { italian: 'Il bok choy', english: 'Bok choy', urdu: 'بوک چوئی' },
      { italian: 'Il ravanello', english: 'The radish', urdu: 'مولی' },
      { italian: 'La rapa', english: 'The turnip', urdu: 'شلجم' },
      { italian: 'La barbabietola', english: 'The beetroot', urdu: 'چقندر' },
      { italian: 'Lo zenzero', english: 'The ginger', urdu: 'ادرک' },
      { italian: 'Il peperoncino', english: 'The chili pepper', urdu: 'ہری مرچ' },
      { italian: 'L\'asparago', english: 'The asparagus', urdu: 'ایسپریگس' },
      { italian: 'Il carciofo', english: 'The artichoke', urdu: 'ہاتھی چک' },
      { italian: 'Il porro', english: 'The leek', urdu: 'لیک' },
      { italian: 'Il cipollotto', english: 'The spring onion', urdu: 'ہری پیاز' },
      { italian: 'Lo scalogno', english: 'The shallot', urdu: 'چھوٹا پیاز' },
      { italian: 'Il sedano', english: 'The celery', urdu: 'اجوائن' },
      { italian: 'Il finocchio', english: 'The fennel', urdu: 'سونف' },
      { italian: 'Il fungo', english: 'The mushroom', urdu: 'کھمبی' },
      { italian: 'Il tartufo', english: 'The truffle', urdu: 'ٹرفل' },
      { italian: 'La patata dolce', english: 'Sweet potato', urdu: 'شکر قندی' },
      { italian: 'Il cece', english: 'Chickpea', urdu: 'چنا' },
      { italian: 'La lenticchia', english: 'Lentil', urdu: 'دال' },
      { italian: 'Il fagiolo', english: 'Bean', urdu: 'پھلی' },
      { italian: 'Il fagiolino', english: 'Green bean', urdu: 'ہری پھلی' },
      { italian: 'L\'ocra', english: 'Okra', urdu: 'بھنڈی' },
      { italian: 'La zucca', english: 'The pumpkin', urdu: 'کدو' },
      { italian: 'La rucola', english: 'Arugula', urdu: 'اروکولا' },
      { italian: 'Il crescione', english: 'Watercress', urdu: 'کریس' },
      { italian: 'L\'indivia', english: 'Endive', urdu: 'اینڈائیو' },
      { italian: 'Il radicchio', english: 'Radicchio', urdu: 'ریڈیکیو' },
      { italian: 'La bietola', english: 'Chard', urdu: 'چارڈ' },
      { italian: 'Il rafano', english: 'Horseradish', urdu: 'ہارسریڈش' },
      { italian: 'Il pastinaca', english: 'Parsnip', urdu: 'سفید گاجر' },
      { italian: 'Il cavolo rapa', english: 'Kohlrabi', urdu: 'گنڈ گوبھی' },
      { italian: 'Il sedano rapa', english: 'Celeriac', urdu: 'سیلیریک' },
      { italian: 'Il taro', english: 'Taro', urdu: 'اروی' },
      { italian: 'La manioca', english: 'Cassava', urdu: 'مانیوکا' },
      { italian: 'Il germoglio di bambù', english: 'Bamboo shoot', urdu: 'بانس کا شاخ' },
      { italian: 'La zucchina', english: 'The marrow', urdu: 'کدو' },
      { italian: 'Il cavolo cinese', english: 'Chinese cabbage', urdu: 'چینی گوبھی' },
      { italian: 'La batata', english: 'Yam', urdu: 'یام' },
      { italian: 'Il lupino', english: 'Lupin', urdu: 'لوپین' },
      { italian: 'Il cardo', english: 'Cardoon', urdu: 'کارڈون' },
      { italian: 'La scorzonera', english: 'Salsify', urdu: 'سیلسفی' },
      { italian: 'Il topinambur', english: 'Jerusalem artichoke', urdu: 'یروشلم آرٹیکوک' },
      { italian: 'L\'alga', english: 'Seaweed', urdu: 'سمندری گھاس' },
      { italian: 'Il cappero', english: 'Caper', urdu: 'کیپر' },
      { italian: 'L\'oliva', english: 'Olive', urdu: 'زیتون' },
      { italian: 'La soia', english: 'Soybean', urdu: 'سویا بین' },
      { italian: 'Il germoglio', english: 'Sprout', urdu: 'کونپل' },
      // 50 additional vegetables words
      { italian: 'Il daikon', english: 'Daikon', urdu: 'ڈائیکون' },
      { italian: 'La scarola', english: 'Escarole', urdu: 'ایسکیرول' },
      { italian: 'Il radicchio trevigiano', english: 'Treviso chicory', urdu: 'ٹریبیسو چکوری' },
      { italian: 'Il songino', english: 'Lamb\'s lettuce', urdu: 'میمنے کا سلاد' },
      { italian: 'La valeriana', english: 'Valerian lettuce', urdu: 'ویلیرین سلاد' },
      { italian: 'L\'erba cipollina', english: 'Chives', urdu: 'ہرا پیاز' },
      { italian: 'Il prezzemolo', english: 'Parsley', urdu: 'اجوائن کے پتے' },
      { italian: 'Il basilico', english: 'Basil', urdu: 'تلسی' },
      { italian: 'L\'origano', english: 'Oregano', urdu: 'اوریگانو' },
      { italian: 'Il rosmarino', english: 'Rosemary', urdu: 'روزمیری' },
      { italian: 'La salvia', english: 'Sage', urdu: 'سیج' },
      { italian: 'Il timo', english: 'Thyme', urdu: 'تھائم' },
      { italian: 'La menta', english: 'Mint', urdu: 'پودینہ' },
      { italian: 'La maggiorana', english: 'Marjoram', urdu: 'مرجورم' },
      { italian: 'Il coriandolo', english: 'Cilantro', urdu: 'دھنیا' },
      { italian: 'L\'aneto', english: 'Dill', urdu: 'سویا' },
      { italian: 'L\'alloro', english: 'Bay leaf', urdu: 'تیز پات' },
      { italian: 'Lo zafferano', english: 'Saffron', urdu: 'زعفران' },
      { italian: 'La curcuma', english: 'Turmeric', urdu: 'ہلدی' },
      { italian: 'La senape', english: 'Mustard', urdu: 'سرسوں' },
      { italian: 'Il rafano nero', english: 'Black radish', urdu: 'کالی مولی' },
      { italian: 'Il sedano bianco', english: 'White celery', urdu: 'سفید اجوائن' },
      { italian: 'La bietola rossa', english: 'Red chard', urdu: 'سرخ بیٹولا' },
      { italian: 'Il peperoncino piccante', english: 'Hot chili', urdu: 'تیز مرچ' },
      { italian: 'La melanzana tonda', english: 'Round eggplant', urdu: 'گول بینگن' },
      { italian: 'Il pomodoro ciliegino', english: 'Cherry tomato', urdu: 'چیری ٹماٹر' },
      { italian: 'Il pomodoro ramato', english: 'Vine tomato', urdu: 'بیل والا ٹماٹر' },
      { italian: 'Il carciofo sardo', english: 'Sardinian artichoke', urdu: 'سارڈینین آرٹیکوک' },
      { italian: 'La fava', english: 'Broad bean', urdu: 'بڑی پھلی' },
      { italian: 'Il lupino bianco', english: 'White lupin', urdu: 'سفید لوپن' },
      { italian: 'Il fagiolo borlotto', english: 'Borlotti bean', urdu: 'بورلوٹی بین' },
      { italian: 'Il fagiolo cannellino', english: 'Cannellini bean', urdu: 'کینیلی بین' },
      { italian: 'La lenticchia rossa', english: 'Red lentil', urdu: 'سرخ دال' },
      { italian: 'La lenticchia di Castelluccio', english: 'Castelluccio lentil', urdu: 'کاسٹیلوچیو دال' },
      { italian: 'Il pisello mangiatutto', english: 'Snow pea', urdu: 'کھانے والی پھلی' },
      { italian: 'Il germoglio di soia', english: 'Soy sprout', urdu: 'سویا کونپل' },
      { italian: 'Il germoglio di alfa-alfa', english: 'Alfalfa sprout', urdu: 'الافالفا کونپل' },
      { italian: 'L\'alga nori', english: 'Nori seaweed', urdu: 'نوری کائی' },
      { italian: 'L\'alga wakame', english: 'Wakame seaweed', urdu: 'واکامی کائی' },
      { italian: 'Il fungo porcino', english: 'Porcini mushroom', urdu: 'پورچینی کھمبی' },
      { italian: 'Il fungo champignon', english: 'Button mushroom', urdu: 'بٹن کھمبی' },
      { italian: 'Il fungo pleurotus', english: 'Oyster mushroom', urdu: 'سیپی کھمبی' },
      { italian: 'Il fungo finferlo', english: 'Chanterelle', urdu: 'چانٹریل کھمبی' },
      { italian: 'Il tartufo nero', english: 'Black truffle', urdu: 'کالا ٹرفل' },
      { italian: 'Il tartufo bianco', english: 'White truffle', urdu: 'سفید ٹرفل' },
      { italian: 'La verza', english: 'Savoy cabbage', urdu: 'سووائے گوبھی' },
      { italian: 'Il broccolo romano', english: 'Romanesco broccoli', urdu: 'رومی بروکولی' },
      { italian: 'La cima di rapa', english: 'Turnip tops', urdu: 'شلجم کی ٹاپ' },
      { italian: 'Il radicchio di Chioggia', english: 'Chioggia radicchio', urdu: 'چیگیا ریڈیکیو' },
      { italian: 'La barba di frate', english: 'Agretti', urdu: 'اگریٹی' }
    ]
  },
  {
    id: 'fruits',
    title: 'Frutta',
    subtitle: 'Fruits',
    imageUrl: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?q=80&w=1470&auto=format&fit=crop',
    icon: 'eco',
    items: [
      { italian: 'La mela', english: 'The apple', urdu: 'سیب' },
      { italian: 'La banana', english: 'The banana', urdu: 'کیلا' },
      { italian: 'L\'arancia', english: 'The orange', urdu: 'مالٹا' },
      { italian: 'La fragola', english: 'The strawberry', urdu: 'سٹرابیری' },
      { italian: 'L\'uva', english: 'The grapes', urdu: 'انگور' },
      { italian: 'Il limone', english: 'The lemon', urdu: 'لیموں' },
      { italian: 'La pera', english: 'The pear', urdu: 'ناشپاتی' },
      { italian: 'L\'ananas', english: 'The pineapple', urdu: 'اناناس' },
      { italian: 'La pesca', english: 'The peach', urdu: 'آڑو' },
      { italian: 'L\'anguria', english: 'The watermelon', urdu: 'تربوز' },
      { italian: 'La ciliegia', english: 'The cherry', urdu: 'چیری' },
      { italian: 'Il kiwi', english: 'The kiwi', urdu: 'کیوی' },
      { italian: 'Il mango', english: 'The mango', urdu: 'آم' },
      { italian: 'Il mirtillo', english: 'The blueberry', urdu: 'نیل بدری' },
      { italian: 'Il lampone', english: 'The raspberry', urdu: 'رس بھری' },
      { italian: 'La mora', english: 'The blackberry', urdu: 'سیاہ بیری' },
      { italian: 'Il mirtillo rosso', english: 'The cranberry', urdu: 'کرین بیری' },
      { italian: 'La bacca di goji', english: 'The goji berry', urdu: 'گوجی بیری' },
      { italian: 'La melagrana', english: 'The pomegranate', urdu: 'انار' },
      { italian: 'La papaya', english: 'The papaya', urdu: 'پپیتا' },
      { italian: 'La guava', english: 'The guava', urdu: 'امرود' },
      { italian: 'Il frutto della passione', english: 'Passion fruit', urdu: 'پیشن فروٹ' },
      { italian: 'Il frutto del drago', english: 'Dragon fruit', urdu: 'ڈریگن فروٹ' },
      { italian: 'La carambola', english: 'Star fruit', urdu: 'ستارہ پھل' },
      { italian: 'Il litchi', english: 'The lychee', urdu: 'لیچی' },
      { italian: 'Il rambutan', english: 'The rambutan', urdu: 'رمبوتان' },
      { italian: 'Il durian', english: 'The durian', urdu: 'دوریان' },
      { italian: 'Il giaca', english: 'The jackfruit', urdu: 'کٹہل' },
      { italian: 'Il mangostano', english: 'The mangosteen', urdu: 'منگوسٹین' },
      { italian: 'Il cachi', english: 'The persimmon', urdu: 'جاپانی پھل' },
      { italian: 'Il fico', english: 'The fig', urdu: 'انجیر' },
      { italian: 'Il dattero', english: 'The date', urdu: 'کھجور' },
      { italian: 'L\'albicocca', english: 'The apricot', urdu: 'خوبانی' },
      { italian: 'La prugna', english: 'The plum', urdu: 'آلو بخارا' },
      { italian: 'La prugna secca', english: 'The prune', urdu: 'خشک آلو بخارا' },
      { italian: 'La nettarina', english: 'The nectarine', urdu: 'نیپٹارین' },
      { italian: 'La clementina', english: 'The clementine', urdu: 'کلیمینٹائن' },
      { italian: 'Il mandarino', english: 'The mandarin', urdu: 'کینو' },
      { italian: 'Il pompelmo', english: 'The grapefruit', urdu: 'چکوترا' },
      { italian: 'Il pomelo', english: 'The pomelo', urdu: 'پومیلو' },
      { italian: 'La limetta', english: 'The lime', urdu: 'موسمبی' },
      { italian: 'L\'avocado', english: 'The avocado', urdu: 'ایوکاڈو' },
      { italian: 'Il cocco', english: 'The coconut', urdu: 'ناریل' },
      { italian: 'L\'oliva', english: 'The olive', urdu: 'زیتون' },
      { italian: 'Il rabarbaro', english: 'The rhubarb', urdu: 'ریوند چینی' },
      { italian: 'Il melone', english: 'The cantaloupe', urdu: 'خربوزہ' },
      { italian: 'L\'uva passa', english: 'The raisin', urdu: 'کشمش' },
      { italian: 'Il ribes', english: 'The currant', urdu: 'کرنٹ' },
      { italian: 'Il sambuco', english: 'The elderberry', urdu: 'ایلڈربیری' },
      { italian: 'Il gelso', english: 'The mulberry', urdu: 'شہتوت' },
      { italian: 'L\'uva spina', english: 'The gooseberry', urdu: 'گوزبیری' },
      { italian: 'La nespola', english: 'The loquat', urdu: 'لوکاٹ' },
      { italian: 'La mela cotogna', english: 'The quince', urdu: 'سفرجل' },
      { italian: 'L\'annona', english: 'The custard apple', urdu: 'شریفہ' },
      { italian: 'Il pomodoro', english: 'The tomato', urdu: 'ٹماٹر' },
      { italian: 'Il pomelo', english: 'The pomelo', urdu: 'بڑا چکوترہ' },
      { italian: 'Il ribes nero', english: 'Blackcurrant', urdu: 'کالا کرنٹ' },
      { italian: 'Il ribes rosso', english: 'Redcurrant', urdu: 'سرخ کرنٹ' },
      { italian: 'La castagna', english: 'Chestnut', urdu: 'شاہ بلوط' },
      { italian: 'La noce', english: 'Walnut', urdu: 'اخروٹ' },
      { italian: 'La mandorla', english: 'Almond', urdu: 'بادام' },
      { italian: 'Il pistacchio', english: 'Pistachio', urdu: 'پستہ' },
      { italian: 'La nocciola', english: 'Hazelnut', urdu: 'بندق' },
      // 50 additional fruits words
      { italian: 'Il kumquat', english: 'Kumquat', urdu: 'کمکواٹ' },
      { italian: 'Il mandarancio', english: 'Clementine-Orange cross', urdu: 'مندرانی' },
      { italian: 'La nespola del Giappone', english: 'Japanese loquat', urdu: 'جاپانی لوکاٹ' },
      { italian: 'Il bergamotto', english: 'Bergamot', urdu: 'برگاموٹ' },
      { italian: 'Il cedro', english: 'Citron', urdu: 'چکوترا' },
      { italian: 'Il chinotto', english: 'Chinotto', urdu: 'چینوٹو' },
      { italian: 'La mela annurca', english: 'Annurca apple', urdu: 'انورکا سیب' },
      { italian: 'La mela cotogna', english: 'Quince', urdu: 'بہہ' },
      { italian: 'La pera coscia', english: 'Coscia pear', urdu: 'کوشیا ناشپاتی' },
      { italian: 'La pera abate', english: 'Abate pear', urdu: 'ایبیٹ ناشپاتی' },
      { italian: 'Il fico d\'India', english: 'Prickly pear', urdu: 'زقوم' },
      { italian: 'Il corbezzolo', english: 'Strawberry tree fruit', urdu: 'سٹرابیری درخت کا پھل' },
      { italian: 'La giuggiola', english: 'Jujube', urdu: 'عناب' },
      { italian: 'Il sorbo', english: 'Sorbus fruit', urdu: 'سوربس پھل' },
      { italian: 'L\'azzeruolo', english: 'Azerole', urdu: 'ایزرول' },
      { italian: 'La marasca', english: 'Marasca cherry', urdu: 'ماراسکا چیری' },
      { italian: 'L\'amarena', english: 'Sour cherry', urdu: 'کھٹی چیری' },
      { italian: 'Il durone', english: 'Big cherry', urdu: 'بڑی چیری' },
      { italian: 'Il melone di Cantalupo', english: 'Cantaloupe melon', urdu: 'کینٹالوپ خربوزہ' },
      { italian: 'Il melone giallo', english: 'Winter melon', urdu: 'پیلا خربوزہ' },
      { italian: 'L\'uva fragola', english: 'Strawberry grape', urdu: 'سٹرابیری انگور' },
      { italian: 'L\'uva sultanina', english: 'Sultana grape', urdu: 'سلطانہ انگور' },
      { italian: 'L\'uva passa', english: 'Raisins', urdu: 'کشمش' },
      { italian: 'L\'arachide', english: 'Peanut', urdu: 'مونگ پھلی' },
      { italian: 'L\'anacardio', english: 'Cashew', urdu: 'کاجو' },
      { italian: 'Il pinolo', english: 'Pine nut', urdu: 'چلغوزہ' },
      { italian: 'La noce pecan', english: 'Pecan', urdu: 'پیکان' },
      { italian: 'La noce del Brasile', english: 'Brazil nut', urdu: 'برازیل نٹ' },
      { italian: 'La noce di macadamia', english: 'Macadamia nut', urdu: 'میکادامیا نٹ' },
      { italian: 'Il mirtillo nero', english: 'Bilberry', urdu: 'نیلی بیری' },
      { italian: 'Il mirtillo palustre', english: 'Bog bilberry', urdu: 'دلدلی بیری' },
      { italian: 'L\'olivello spinoso', english: 'Sea buckthorn', urdu: 'سمندری بکتھورن' },
      { italian: 'La bacca di ginepro', english: 'Juniper berry', urdu: 'جونیپر بیری' },
      { italian: 'La rosa canina', english: 'Rose hip', urdu: 'گلاب کا پھل' },
      { italian: 'Il frutto di cactus', english: 'Cactus fruit', urdu: 'کیکٹس کا پھل' },
      { italian: 'L\'ugni', english: 'Chilean guava', urdu: 'چیلی گواوا' },
      { italian: 'La feijoa', english: 'Feijoa', urdu: 'فیجوا' },
      { italian: 'La cherimoya', english: 'Cherimoya', urdu: 'چیریمویا' },
      { italian: 'La sapodilla', english: 'Sapodilla', urdu: 'چیکو' },
      { italian: 'La pitaya', english: 'Dragon fruit', urdu: 'ڈریگن فروٹ' },
      { italian: 'La salak', english: 'Snake fruit', urdu: 'سانپ پھل' },
      { italian: 'Il kiwano', english: 'Horned melon', urdu: 'سینگ والا خربوزہ' },
      { italian: 'La maracuja', english: 'Passion fruit', urdu: 'ماراکوجا' },
      { italian: 'Il tamarindo', english: 'Tamarind', urdu: 'املی' },
      { italian: 'Il platano', english: 'Plantain', urdu: 'کچا کیلا' },
      { italian: 'Il limequat', english: 'Limequat', urdu: 'لائم کواٹ' },
      { italian: 'La pomelia', english: 'Pomelia', urdu: 'پومیلی' },
      { italian: 'Il longan', english: 'Longan', urdu: 'لونگن' },
      { italian: 'La bignonia', english: 'Bignonia', urdu: 'بگنونیا' },
      { italian: 'Il fico secco', english: 'Dried fig', urdu: 'خشک انجیر' }
    ]
  },
  {
    id: 'plants',
    title: 'Le Piante',
    subtitle: 'Plants & Flowers',
    imageUrl: 'https://images.unsplash.com/photo-1545241047-6083a3684587?q=80&w=1374&auto=format&fit=crop',
    icon: 'potted_plant',
    items: [
      { italian: 'Il fiore', english: 'The flower', urdu: 'پھول' },
      { italian: 'L\'albero', english: 'The tree', urdu: 'درخت' },
      { italian: 'La foglia', english: 'The leaf', urdu: 'پتا' },
      { italian: 'L\'erba', english: 'The grass', urdu: 'گھاس' },
      { italian: 'La radice', english: 'The root', urdu: 'جڑ' },
      { italian: 'Il fusto', english: 'The stem', urdu: 'تنا' },
      { italian: 'Il seme', english: 'The seed', urdu: 'بیج' },
      { italian: 'Il ramo', english: 'The branch', urdu: 'شاخ' },
      { italian: 'La rosa', english: 'The rose', urdu: 'گلاب' },
      { italian: 'Il giglio', english: 'The lily', urdu: 'سوسن' },
      { italian: 'Il girasole', english: 'The sunflower', urdu: 'سورج مکھی' },
      { italian: 'Il tulipano', english: 'The tulip', urdu: 'گل لالہ' },
      { italian: 'La margherita', english: 'The daisy', urdu: 'گل بہار' },
      { italian: 'L\'orchidea', english: 'The orchid', urdu: 'آرکڈ' },
      { italian: 'Il cactus', english: 'The cactus', urdu: 'ناگ پھنی' },
      { italian: 'La felce', english: 'The fern', urdu: 'فرن' },
      { italian: 'Il muschio', english: 'The moss', urdu: 'کائی' },
      { italian: 'Il pino', english: 'The pine', urdu: 'صنوبر' },
      { italian: 'La quercia', english: 'The oak', urdu: 'بلوط' },
      { italian: 'L\'acero', english: 'The maple', urdu: 'میپل' },
      { italian: 'Il salice', english: 'The willow', urdu: 'بید' },
      { italian: 'L\'olivo', english: 'The olive tree', urdu: 'زیتون کا درخت' },
      { italian: 'Il melo', english: 'The apple tree', urdu: 'سیب کا درخت' },
      { italian: 'Il ciliegio', english: 'The cherry tree', urdu: 'چیری کا درخت' },
      { italian: 'La palma', english: 'The palm tree', urdu: 'کھجور کا درخت' },
      { italian: 'Il bambù', english: 'The bamboo', urdu: 'بانس' },
      { italian: 'L\'edera', english: 'The ivy', urdu: 'عشق پیچاں' },
      { italian: 'La lavanda', english: 'The lavender', urdu: 'لیونڈر' },
      { italian: 'Il rosmarino', english: 'The rosemary', urdu: 'اکلیل کوہستانی' },
      { italian: 'La salvia', english: 'The sage', urdu: 'سیج' },
      { italian: 'Il basilico', english: 'The basil', urdu: 'تلسی' },
      { italian: 'La menta', english: 'The mint', urdu: 'پودینہ' },
      { italian: 'Il prezzemolo', english: 'The parsley', urdu: 'اجوائن کے پتے' },
      { italian: 'L\'origano', english: 'The oregano', urdu: 'اوریگانو' },
      { italian: 'Il timo', english: 'The thyme', urdu: 'تھائم' },
      { italian: 'L\'ortica', english: 'The nettle', urdu: 'بچھو بوٹی' },
      { italian: 'Il trifoglio', english: 'The clover', urdu: 'تپتیا' },
      { italian: 'Il dente di leone', english: 'The dandelion', urdu: 'ککروندہ' },
      { italian: 'La canna', english: 'The reed', urdu: 'سرکنڈا' },
      { italian: 'Il grano', english: 'The wheat', urdu: 'گندم' },
      { italian: 'Il riso', english: 'The rice', urdu: 'چاول' },
      { italian: 'L\'orzo', english: 'The barley', urdu: 'جو' },
      { italian: 'L\'avena', english: 'The oats', urdu: 'جئی' },
      { italian: 'Il mais', english: 'The corn', urdu: 'مکئی' },
      { italian: 'Il cotone', english: 'The cotton', urdu: 'کپاس' },
      { italian: 'Il lino', english: 'The flax', urdu: 'السی' },
      { italian: 'La canapa', english: 'The hemp', urdu: 'بھنگ' },
      { italian: 'Il tabacco', english: 'The tobacco', urdu: 'تمباکو' },
      { italian: 'La vite', english: 'The grapevine', urdu: 'انگور کی بیل' },
      { italian: 'Il fungo', english: 'The mushroom', urdu: 'کھمبی' }
    ]
  },
  {
    id: 'animals',
    title: 'Gli Animali',
    subtitle: 'Animals & Pets',
    imageUrl: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?q=80&w=1459&auto=format&fit=crop',
    icon: 'pets',
    items: [
      { italian: 'Il cane', english: 'The dog', urdu: 'کتا' },
      { italian: 'Il gatto', english: 'The cat', urdu: 'بلی' },
      { italian: 'Il cavallo', english: 'The horse', urdu: 'گھوڑا' },
      { italian: 'La mucca', english: 'The cow', urdu: 'گائے' },
      { italian: 'Il maiale', english: 'The pig', urdu: 'سور' },
      { italian: 'La pecora', english: 'The sheep', urdu: 'بھیڑ' },
      { italian: 'La capra', english: 'The goat', urdu: 'بکری' },
      { italian: 'Il pollo', english: 'The chicken', urdu: 'مرغی' },
      { italian: 'Il gallo', english: 'The rooster', urdu: 'مرغا' },
      { italian: 'L\'anatra', english: 'The duck', urdu: 'بطخ' },
      { italian: 'L\'oca', english: 'The goose', urdu: 'ہنس' },
      { italian: 'Il coniglio', english: 'The rabbit', urdu: 'خرگوش' },
      { italian: 'Il topo', english: 'The mouse', urdu: 'چوہا' },
      { italian: 'Il leone', english: 'The lion', urdu: 'شیر' },
      { italian: 'La tigre', english: 'The tiger', urdu: 'چیتا' },
      { italian: 'L\'elefante', english: 'The elephant', urdu: 'ہاتھی' },
      { italian: 'La giraffa', english: 'The giraffe', urdu: 'زرافہ' },
      { italian: 'La zebra', english: 'The zebra', urdu: 'زیبرا' },
      { italian: 'L\'orso', english: 'The bear', urdu: 'ریچھ' },
      { italian: 'Il lupo', english: 'The wolf', urdu: 'بھیڑیا' },
      { italian: 'La volpe', english: 'The fox', urdu: 'لومڑی' },
      { italian: 'La scimmia', english: 'The monkey', urdu: 'بندر' },
      { italian: 'Il gorilla', english: 'The gorilla', urdu: 'گوریلا' },
      { italian: 'Lo scimpanzé', english: 'The chimpanzee', urdu: 'چمپانزی' },
      { italian: 'Il canguro', english: 'The kangaroo', urdu: 'کینگرو' },
      { italian: 'Il cammello', english: 'The camel', urdu: 'اونٹ' },
      { italian: 'L\'ippopotamo', english: 'The hippopotamus', urdu: 'دریائی گھوڑا' },
      { italian: 'Il rinoceronte', english: 'The rhinoceros', urdu: 'گینڈا' },
      { italian: 'Il coccodrillo', english: 'The crocodile', urdu: 'مگرمچھ' },
      { italian: 'Il serpente', english: 'The snake', urdu: 'سانپ' },
      { italian: 'La tartaruga', english: 'The turtle', urdu: 'کچھی' },
      { italian: 'La rana', english: 'The frog', urdu: 'مینڈک' },
      { italian: 'Il pesce', english: 'The fish', urdu: 'مچھلی' },
      { italian: 'Lo squalo', english: 'The shark', urdu: 'شارک' },
      { italian: 'La balena', english: 'The whale', urdu: 'وہیل' },
      { italian: 'Il delfino', english: 'The dolphin', urdu: 'ڈولفن' },
      { italian: 'L\'uccello', english: 'The bird', urdu: 'پرندہ' },
      { italian: 'L\'aquila', english: 'The eagle', urdu: 'عقاب' },
      { italian: 'Il falco', english: 'The hawk', urdu: 'باز' },
      { italian: 'Il gufo', english: 'The owl', urdu: 'الو' },
      { italian: 'Il pappagallo', english: 'The parrot', urdu: 'طوطا' },
      { italian: 'Il passero', english: 'The sparrow', urdu: 'چڑیا' },
      { italian: 'Il corvo', english: 'The crow', urdu: 'کوا' },
      { italian: 'Il piccione', english: 'The pigeon', urdu: 'کبوتر' },
      { italian: 'La farfalla', english: 'The butterfly', urdu: 'تتلی' },
      { italian: 'L\'ape', english: 'The bee', urdu: 'شہد کی مکھی' },
      { italian: 'La formica', english: 'The ant', urdu: 'چیونٹی' },
      { italian: 'Il ragno', english: 'The spider', urdu: 'مکڑی' },
      { italian: 'La zanzara', english: 'The mosquito', urdu: 'مچھر' },
      { italian: 'La mosca', english: 'The fly', urdu: 'مکھی' }
    ]
  },
  {
    id: 'body-parts',
    title: 'Il Corpo Umano',
    subtitle: 'Human Body Parts',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=1631&auto=format&fit=crop',
    icon: 'accessibility_new',
    items: [
      { italian: 'La testa', english: 'The head', urdu: 'سر' },
      { italian: 'Il viso', english: 'The face', urdu: 'چہرہ' },
      { italian: 'I capelli', english: 'The hair', urdu: 'بال' },
      { italian: 'L\'occhio', english: 'The eye', urdu: 'آنکھ' },
      { italian: 'L\'orecchio', english: 'The ear', urdu: 'کان' },
      { italian: 'Il naso', english: 'The nose', urdu: 'ناک' },
      { italian: 'La bocca', english: 'The mouth', urdu: 'منہ' },
      { italian: 'Le labbra', english: 'The lips', urdu: 'ہونٹ' },
      { italian: 'I denti', english: 'The teeth', urdu: 'دانت' },
      { italian: 'La lingua', english: 'The tongue', urdu: 'زبان' },
      { italian: 'Il collo', english: 'The neck', urdu: 'گردن' },
      { italian: 'La gola', english: 'The throat', urdu: 'گلا' },
      { italian: 'La spalla', english: 'The shoulder', urdu: 'کندھا' },
      { italian: 'Il braccio', english: 'The arm', urdu: 'بازو' },
      { italian: 'Il gomito', english: 'The elbow', urdu: 'کہنی' },
      { italian: 'Il polso', english: 'The wrist', urdu: 'کلائی' },
      { italian: 'La mano', english: 'The hand', urdu: 'ہاتھ' },
      { italian: 'Il dito', english: 'The finger', urdu: 'انگلی' },
      { italian: 'L\'unghia', english: 'The nail', urdu: 'ناخن' },
      { italian: 'Il petto', english: 'The chest', urdu: 'چھاتی' },
      { italian: 'La schiena', english: 'The back', urdu: 'کمر' },
      { italian: 'Lo stomaco', english: 'The stomach', urdu: 'معدہ' },
      { italian: 'La pancia', english: 'The belly', urdu: 'پیٹ' },
      { italian: 'Il cuore', english: 'The heart', urdu: 'دل' },
      { italian: 'I polmoni', english: 'The lungs', urdu: 'پھیپھڑے' },
      { italian: 'Il fegato', english: 'The liver', urdu: 'جگر' },
      { italian: 'Il rene', english: 'The kidney', urdu: 'گردہ' },
      { italian: 'L\'osso', english: 'The bone', urdu: 'ہڈی' },
      { italian: 'Il muscolo', english: 'The muscle', urdu: 'پٹھہ' },
      { italian: 'Il sangue', english: 'The blood', urdu: 'خون' },
      { italian: 'La pelle', english: 'The skin', urdu: 'جلد' },
      { italian: 'La gamba', english: 'The leg', urdu: 'ٹانگ' },
      { italian: 'Il ginocchio', english: 'The knee', urdu: 'گھٹنا' },
      { italian: 'La caviglia', english: 'The ankle', urdu: 'ٹخنہ' },
      { italian: 'Il piede', english: 'The foot', urdu: 'پاؤں' },
      { italian: 'Il tallone', english: 'The heel', urdu: 'ایڑی' },
      { italian: 'Il dito del piede', english: 'The toe', urdu: 'پاؤں کی انگلی' },
      { italian: 'Il cervello', english: 'The brain', urdu: 'دماغ' },
      { italian: 'La fronte', english: 'The forehead', urdu: 'پیشانی' },
      { italian: 'Il sopracciglio', english: 'The eyebrow', urdu: 'بھنویں' },
      { italian: 'Le ciglia', english: 'The eyelashes', urdu: 'پلکیں' },
      { italian: 'La guancia', english: 'The cheek', urdu: 'گال' },
      { italian: 'Il mento', english: 'The chin', urdu: 'ٹھوڑی' },
      { italian: 'La mascella', english: 'The jaw', urdu: 'جبڑا' },
      { italian: 'Il pollice', english: 'The thumb', urdu: 'انگوٹھا' },
      { italian: 'L\'indice', english: 'The index finger', urdu: 'شہادت کی انگلی' },
      { italian: 'Il medio', english: 'The middle finger', urdu: 'درمیانی انگلی' },
      { italian: 'L\'anulare', english: 'The ring finger', urdu: 'چھوٹی انگلی کے ساتھ والی انگلی' },
      { italian: 'Il mignolo', english: 'The pinky finger', urdu: 'چھوٹی انگلی' },
      { italian: 'Il palmo', english: 'The palm', urdu: 'ہتھیلی' }
    ]
  },
  {
    id: 'family',
    title: 'La Famiglia',
    subtitle: 'The Family',
    imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?q=80&w=1470&auto=format&fit=crop',
    icon: 'groups',
    items: [
      { italian: 'La madre', english: 'The mother', urdu: 'ماں' },
      { italian: 'Il padre', english: 'The father', urdu: 'باپ' },
      { italian: 'Il figlio', english: 'The son', urdu: 'بیٹا' },
      { italian: 'La figlia', english: 'The daughter', urdu: 'بیٹی' },
      { italian: 'Il fratello', english: 'The brother', urdu: 'بھائی' },
      { italian: 'La sorella', english: 'The sister', urdu: 'بہن' },
      { italian: 'Il nonno', english: 'The grandfather', urdu: 'دادا/نانا' },
      { italian: 'La nonna', english: 'The grandmother', urdu: 'دادی/نانی' },
      { italian: 'Lo zio', english: 'The uncle', urdu: 'چچا/ماموں' },
      { italian: 'La zia', english: 'The aunt', urdu: 'پھوپھی/خالہ' },
      { italian: 'Il cugino', english: 'The cousin (male)', urdu: 'کزن (مرد)' },
      { italian: 'La cugina', english: 'The cousin (female)', urdu: 'کزن (عورت)' },
      { italian: 'Il nipote', english: 'The nephew/grandson', urdu: 'بھتیجا/پوتا' },
      { italian: 'La nipote', english: 'The niece/granddaughter', urdu: 'بھتیجی/پوتی' },
      { italian: 'Il marito', english: 'The husband', urdu: 'شوہر' },
      { italian: 'La moglie', english: 'The wife', urdu: 'بیوی' },
      { italian: 'I genitori', english: 'The parents', urdu: 'والدین' },
      { italian: 'I parenti', english: 'The relatives', urdu: 'رشتہ دار' },
      { italian: 'Il suocero', english: 'The father-in-law', urdu: 'سسر' },
      { italian: 'La suocera', english: 'The mother-in-law', urdu: 'ساس' },
      { italian: 'Il genero', english: 'The son-in-law', urdu: 'داماد' },
      { italian: 'La nuora', english: 'The daughter-in-law', urdu: 'بہو' },
      { italian: 'Il cognato', english: 'The brother-in-law', urdu: 'سالا/بہنوئی' },
      { italian: 'La cognata', english: 'The sister-in-law', urdu: 'سالی/بھابی' },
      { italian: 'Il patrigno', english: 'The stepfather', urdu: 'سوتیلا باپ' },
      { italian: 'La matrigna', english: 'The stepmother', urdu: 'سوتیلی ماں' },
      { italian: 'Il figliastro', english: 'The stepson', urdu: 'سوتیلا بیٹا' },
      { italian: 'La figliastra', english: 'The stepdaughter', urdu: 'سوتیلی بیٹی' },
      { italian: 'Il fratellastro', english: 'The stepbrother', urdu: 'سوتیلا بھائی' },
      { italian: 'La sorellastra', english: 'The stepsister', urdu: 'سوتیلی بہن' },
      { italian: 'Il bisnonno', english: 'The great-grandfather', urdu: 'پردادا/پرنانا' },
      { italian: 'La bisnonna', english: 'The great-grandmother', urdu: 'پردادی/پرنانی' },
      { italian: 'Il pronipote', english: 'The great-grandson', urdu: 'پڑپوتا/پڑنواسا' },
      { italian: 'La pronipote', english: 'The great-granddaughter', urdu: 'پڑپوتی/پڑنواسی' },
      { italian: 'I nonni', english: 'The grandparents', urdu: 'دادا دادی/نانا نانی' },
      { italian: 'I figli', english: 'The children/sons', urdu: 'بچے' },
      { italian: 'I fratelli', english: 'The siblings', urdu: 'بہن بھائی' },
      { italian: 'Il gemello', english: 'The twin brother', urdu: 'جڑواں بھائی' },
      { italian: 'La gemella', english: 'The twin sister', urdu: 'جڑواں بہن' },
      { italian: 'I gemelli', english: 'The twins', urdu: 'جڑواں' },
      { italian: 'Lo sposo', english: 'The groom', urdu: 'دولہا' },
      { italian: 'La sposa', english: 'The bride', urdu: 'دلہن' },
      { italian: 'Il fidanzato', english: 'The fiancé/boyfriend', urdu: 'منگیتر (مرد)' },
      { italian: 'La fidanzata', english: 'The fiancée/girlfriend', urdu: 'منگیتر (عورت)' },
      { italian: 'Il matrimonio', english: 'The marriage/wedding', urdu: 'شادی' },
      { italian: 'Il divorzio', english: 'The divorce', urdu: 'طلاق' },
      { italian: 'La famiglia allargata', english: 'The extended family', urdu: 'بڑا خاندان' },
      { italian: 'L\'antenato', english: 'The ancestor', urdu: 'آباؤ اجداد' },
      { italian: 'Il vedovo', english: 'The widower', urdu: 'رنڈوا' },
      { italian: 'La vedova', english: 'The widow', urdu: 'بیوہ' },
      { italian: 'Il compagno', english: 'The partner (male)', urdu: 'ساتھی (مرد)' },
      { italian: 'La compagna', english: 'The partner (female)', urdu: 'ساتھی (عورت)' },
      { italian: 'Il bebè', english: 'The baby', urdu: 'بچہ' },
      { italian: 'L\'infanzia', english: 'The childhood', urdu: 'بچپن' }
    ]
  },
  {
    id: 'time-days',
    title: 'Tempo e Giorni',
    subtitle: 'Time & Days',
    imageUrl: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?q=80&w=1470&auto=format&fit=crop',
    icon: 'schedule',
    items: [
      { italian: 'Lunedì', english: 'Monday', urdu: 'پیر' },
      { italian: 'Martedì', english: 'Tuesday', urdu: 'منگل' },
      { italian: 'Mercoledì', english: 'Wednesday', urdu: 'بدھ' },
      { italian: 'Giovedì', english: 'Thursday', urdu: 'جمعرات' },
      { italian: 'Venerdì', english: 'Friday', urdu: 'جمعہ' },
      { italian: 'Sabato', english: 'Saturday', urdu: 'ہفتہ' },
      { italian: 'Domenica', english: 'Sunday', urdu: 'اتوار' },
      { italian: 'Oggi', english: 'Today', urdu: 'آج' },
      { italian: 'Ieri', english: 'Yesterday', urdu: 'کل (گزرا ہوا)' },
      { italian: 'Domani', english: 'Tomorrow', urdu: 'کل (آنے والا)' },
      { italian: 'La settimana', english: 'The week', urdu: 'ہفتہ' },
      { italian: 'Il mese', english: 'The month', urdu: 'مہینہ' },
      { italian: 'L\'anno', english: 'The year', urdu: 'سال' },
      { italian: 'L\'ora', english: 'The hour/time', urdu: 'گھنٹہ/وقت' },
      { italian: 'Il minuto', english: 'The minute', urdu: 'منٹ' },
      { italian: 'Il secondo', english: 'The second', urdu: 'سیکنڈ' },
      { italian: 'Il fine settimana', english: 'The weekend', urdu: 'ویک اینڈ' },
      { italian: 'L\'altro ieri', english: 'The day before yesterday', urdu: 'پرسوں (گزرا ہوا)' },
      { italian: 'Dopodomani', english: 'The day after tomorrow', urdu: 'پرسوں (آنے والا)' },
      { italian: 'Il mattino', english: 'The morning', urdu: 'صبح' },
      { italian: 'Il pomeriggio', english: 'The afternoon', urdu: 'دوپہر' },
      { italian: 'La sera', english: 'The evening', urdu: 'شام' },
      { italian: 'La notte', english: 'The night', urdu: 'رات' },
      { italian: 'Mezzogiorno', english: 'Noon', urdu: 'دوپہر بارہ بجے' },
      { italian: 'Mezzanotte', english: 'Midnight', urdu: 'آدھی رات' },
      { italian: 'L\'alba', english: 'The dawn', urdu: 'فجر/طلوع آفتاب' },
      { italian: 'Il tramonto', english: 'The sunset', urdu: 'غروب آفتاب' },
      { italian: 'Il secolo', english: 'The century', urdu: 'صدی' },
      { italian: 'Il decennio', english: 'The decade', urdu: 'دہائی' },
      { italian: 'Il millennio', english: 'The millennium', urdu: 'ہزار سال' },
      { italian: 'Gennaio', english: 'January', urdu: 'جنوری' },
      { italian: 'Febbraio', english: 'February', urdu: 'فروری' },
      { italian: 'Marzo', english: 'March', urdu: 'مارچ' },
      { italian: 'Aprile', english: 'April', urdu: 'اپریل' },
      { italian: 'Maggio', english: 'May', urdu: 'مئی' },
      { italian: 'Giugno', english: 'June', urdu: 'جون' },
      { italian: 'Luglio', english: 'July', urdu: 'جولائی' },
      { italian: 'Agosto', english: 'August', urdu: 'اگست' },
      { italian: 'Settembre', english: 'September', urdu: 'ستمبر' },
      { italian: 'Ottobre', english: 'October', urdu: 'اکتوبر' },
      { italian: 'Novembre', english: 'November', urdu: 'نومبر' },
      { italian: 'Dicembre', english: 'December', urdu: 'دسمبر' },
      { italian: 'La primavera', english: 'The spring', urdu: 'بہار' },
      { italian: 'L\'estate', english: 'The summer', urdu: 'گرمی' },
      { italian: 'L\'autunno', english: 'The autumn', urdu: 'خزاں' },
      { italian: 'L\'inverno', english: 'The winter', urdu: 'سردی' },
      { italian: 'La stagione', english: 'The season', urdu: 'موسم' },
      { italian: 'Il calendario', english: 'The calendar', urdu: 'کیلنڈر' },
      { italian: 'L\'orologio', english: 'The clock/watch', urdu: 'گھڑی' },
      { italian: 'Presto', english: 'Early', urdu: 'جلدی' },
      { italian: 'Tardi', english: 'Late', urdu: 'دیر سے' },
      { italian: 'Adesso', english: 'Now', urdu: 'اب' },
      { italian: 'Dopo', english: 'After/Later', urdu: 'بعد میں' },
      { italian: 'Prima', english: 'Before', urdu: 'پہلے' },
      { italian: 'Sempre', english: 'Always', urdu: 'ہمیشہ' },
      { italian: 'Mai', english: 'Never', urdu: 'کبھی نہیں' },
      { italian: 'Spesso', english: 'Often', urdu: 'اکثر' },
      { italian: 'A volte', english: 'Sometimes', urdu: 'کبھی کبھی' }
    ]
  },
  {
    id: 'travel',
    title: 'Viaggi e Trasporti',
    subtitle: 'Travel & Transport',
    imageUrl: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?q=80&w=1631&auto=format&fit=crop',
    icon: 'flight',
    items: [
      { italian: 'L\'aereo', english: 'The airplane', urdu: 'ہوائی جہاز' },
      { italian: 'Il treno', english: 'The train', urdu: 'ٹرین' },
      { italian: 'L\'autobus', english: 'The bus', urdu: 'بس' },
      { italian: 'La macchina', english: 'The car', urdu: 'گاڑی' },
      { italian: 'La bicicletta', english: 'The bicycle', urdu: 'سائیکل' },
      { italian: 'La nave', english: 'The ship', urdu: 'بحری جہاز' },
      { italian: 'Il biglietto', english: 'The ticket', urdu: 'ٹکٹ' },
      { italian: 'La stazione', english: 'The station', urdu: 'اسٹیشن' },
      { italian: 'L\'aeroporto', english: 'The airport', urdu: 'ہوائی اڈہ' },
      { italian: 'La valigia', english: 'The suitcase', urdu: 'سوٹ کیس' },
      { italian: 'Il passaporto', english: 'The passport', urdu: 'پاسپورٹ' },
      { italian: 'L\'hotel', english: 'The hotel', urdu: 'ہوٹل' },
      { italian: 'La prenotazione', english: 'The reservation', urdu: 'بکنگ' },
      { italian: 'La mappa', english: 'The map', urdu: 'نقشہ' },
      { italian: 'Il viaggio', english: 'The trip/journey', urdu: 'سفر' },
      { italian: 'La vacanza', english: 'The holiday/vacation', urdu: 'چھٹی' },
      { italian: 'Il bagaglio', english: 'The luggage', urdu: 'سامان' },
      { italian: 'Il volo', english: 'The flight', urdu: 'پرواز' },
      { italian: 'La partenza', english: 'The departure', urdu: 'روانگی' },
      { italian: 'L\'arrivo', english: 'The arrival', urdu: 'آمد' },
      { italian: 'Il binario', english: 'The platform', urdu: 'پلیٹ فارم' },
      { italian: 'La fermata', english: 'The stop', urdu: 'اسٹاپ' },
      { italian: 'Il passeggero', english: 'The passenger', urdu: 'مسافر' },
      { italian: 'L\'autista', english: 'The driver', urdu: 'ڈرائیور' },
      { italian: 'Il pilota', english: 'The pilot', urdu: 'پائلٹ' },
      { italian: 'Il traghetto', english: 'The ferry', urdu: 'فیری/کشتی' },
      { italian: 'La barca', english: 'The boat', urdu: 'کشتی' },
      { italian: 'La metropolitana', english: 'The subway/metro', urdu: 'میٹرو' },
      { italian: 'Il tram', english: 'The tram', urdu: 'ٹرام' },
      { italian: 'Il taxi', english: 'The taxi', urdu: 'ٹیکسی' },
      { italian: 'La motocicletta', english: 'The motorcycle', urdu: 'موٹر سائیکل' },
      { italian: 'Il camion', english: 'The truck', urdu: 'ٹرک' },
      { italian: 'Il furgone', english: 'The van', urdu: 'وین' },
      { italian: 'L\'elicottero', english: 'The helicopter', urdu: 'ہیلی کاپٹر' },
      { italian: 'Il biglietto di andata e ritorno', english: 'The round-trip ticket', urdu: 'واپسی کا ٹکٹ' },
      { italian: 'La dogana', english: 'The customs', urdu: 'کسٹم' },
      { italian: 'Il visto', english: 'The visa', urdu: 'ویزا' },
      { italian: 'La carta d\'imbarco', english: 'The boarding pass', urdu: 'بورڈنگ پاس' },
      { italian: 'Il controllo passaporti', english: 'The passport control', urdu: 'پاسپورٹ کنٹرول' },
      { italian: 'Il ritardo', english: 'The delay', urdu: 'تاخیر' },
      { italian: 'Il sedile', english: 'The seat', urdu: 'سیٹ' },
      { italian: 'Il finestrino', english: 'The window', urdu: 'کھڑکی' },
      { italian: 'Il corridoio', english: 'The aisle', urdu: 'راستہ' },
      { italian: 'L\'ostello', english: 'The hostel', urdu: 'ہاسٹل' },
      { italian: 'Il campeggio', english: 'The campsite', urdu: 'کیمپنگ' },
      { italian: 'La tenda', english: 'The tent', urdu: 'خیمہ' },
      { italian: 'Il turista', english: 'The tourist', urdu: 'سیاح' },
      { italian: 'La guida turistica', english: 'The tour guide', urdu: 'ٹور گائیڈ' },
      { italian: 'Il monumento', english: 'The monument', urdu: 'یادگار' },
      { italian: 'Il museo', english: 'The museum', urdu: 'عجائب گھر' },
      { italian: 'La spiaggia', english: 'The beach', urdu: 'ساحل' },
      { italian: 'La montagna', english: 'The mountain', urdu: 'پہاڑ' },
      { italian: 'L\'isola', english: 'The island', urdu: 'جزیرہ' },
      { italian: 'La crociera', english: 'The cruise', urdu: 'کروز' },
      { italian: 'Noleggiare', english: 'To rent', urdu: 'کرایہ پر لینا' },
      { italian: 'Guidare', english: 'To drive', urdu: 'گاڑی چلانا' },
      { italian: 'Volare', english: 'To fly', urdu: 'اڑنا' }
    ]
  }
];
